### ISSUE TITLE
Export Typescript type definitions

### ISSUE THREAD

**Issue by haggs** [brandly/react-tetris#23]
Hi,

I want to use this in a Typescript project. I could always declare ambient types, but it looks like you're using TS already. Can the types be exported?

Thanks!

**Comment by brandly** [comment]
Hey, yeah this is a good idea. It was only [recently converted to TypeScript](https://github.com/brandly/react-tetris/pull/19), and no releases have happened since the conversion. I've written a lot of TypeScript but never published packages like this one. I'll have to sort out these details.

**Comment by haggs** [comment]
Thanks Matt. I'm in the same boat. I've written Typescript a lot but only
consumed other typescript libraries. Any help you offer would be greatly
appreciated.

**Comment by brandly** [comment]
@haggs _i believe_ this is now fixed in `v0.3.0`. let me know if it works for you!

**Comment by haggs** [comment]
Thanks for getting back to me! I ended up building my own tetris (I know, I know) for my needs. But I'll let you know here if I get a chance to try it again
