### ISSUE TITLE
document is not defined....

### ISSUE THREAD

**Issue by Shane0531** [brandly/react-tetris#6]
Hello thanks for your effort 

but have error after i upgrade node, npm so i can't webpack build..

/Users/shane/abcl/node_modules/react-tetris/lib/index.js:1464
  addEvent(document, 'keydown', function(event) { dispatch(event); }); // Passing _scope to a callback to ensure it remains the same by execution. Fixes #48
           ^

ReferenceError: document is not defined
    at /Users/shane/abc/node_modules/react-tetris/lib/index.js:1464:12
    at /Users/shane/abc/node_modules/react-tetris/lib/index.js:1493:3
    at createCommonjsModule (/Users/shane/abc/node_modules/react-tetris/lib/index.js:243:35)
    at Object.<anonymous> (/Users/shane/abc/node_modules/react-tetris/lib/index.js:1197:17)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shane/abc/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

my environment 
node v8.11.2, npm v6.1.0, webpack v2.2.0 

you need any other?

**Comment by brandly** [comment]
[try-react-tetris.zip](https://github.com/brandly/react-tetris/files/2059968/try-react-tetris.zip)

here's a tiny project that bundles `react-tetris` with webpack v2.2. it seems to work.

```
$ npm install
$ npm run build
```

---

the `ReferenceError` you're seeing makes it appear as tho webpack is actually executing `react-tetris`, which shouldn't be the case. 

at this point, i'm under the impression that there might be something wrong with your webpack config, not with this repo. closing the issue for now, but if you can recreate this issue in a focused manner, let me know!

**Comment by Shane0531** [comment]
oh i finally found my issue

The problem is that when react-tetris is loaded in node context (where document doesn't exist), it throws the error below.

`
$ node
> var tetris = require('react-tetris')
ReferenceError: document is not defined
    at /Users/shane/makestar-universal/node_modules/react-tetris/lib/index.js:1464:12
    at /Users/shane/makestar-universal/node_modules/react-tetris/lib/index.js:1493:3
    at createCommonjsModule (/Users/shane/makestar-universal/node_modules/react-tetris/lib/index.js:243:35)
`
and this error also occured in detect-shift
`
document.addEventListener('keydown', e => {
  if (e.shiftKey && !isPressed) {
    isPressed = e.shiftKey;
    callCallbacks();
  }

  return true;
});

document.addEventListener('keyup', e => {
  if (!e.shiftKey && isPressed) {
    isPressed = e.shiftKey;
  }

  return true;
});
`

so i stiil find solution 
thank you your effort!

and i have one question
Are you planning to create a feature that can be restarted when the game is over? :)

**Comment by brandly** [comment]
`document` won't ever be defined outside of a browser, so executing this library with node won't work. 

it's breaking when you try to bundle it with webpack? webpack should only be reading/parsing the file, not actually executing it.

> Are you planning to create a feature that can be restarted when the game is over? :)

i don't really have any plans. i cleaned this repo up several months ago, but the bulk of this code has been untouched for a few years.

**Comment by Shane0531** [comment]
it works good when bundle with webpack :)

**Comment by ouya99** [comment]
@Shane0531 could you paste your webpack config please? I am having same issue

>   module: {
    rules: [{
      test: /\.jsx?$/,
      loader: 'babel-loader',
      exclude: /(node_modules|bower_components)/,
      options: {
        presets: ["@babel/react", ["@babel/preset-env", {
          "modules": false
        }]]
      }
    }]
  },

With this config I still get : **ReferenceError: document is not defined**
